travis:
  secure:
    BINSTAR_TOKEN: II6dHTd5j0GfZMQ1P1OntDh9yvhOs03btSUzpHMjZhgYFj09/vIw0YFx4XIsZLYCnzx6FmKvBoSiVeSB0Yu8qDkwc01JhbrU7F++b5yt4ENUTV5a2pHZUMhJvL+Z0v/ZYaObjlb+0e8/Q1NJxbGi2lV73Ze0zfu/57wJkYdzePv2dey21KKgvpAkRUarXeiOcsnG3BEI1cw5lwjqv0WPsM8dO0EH0webL5rlNTuIUlaP2A5BRNe0DYR8NXqBh/71NM73xYdj5SZmJiPI7xqdLR/HfipUe9onBkWxuz7yxHq2HksaCJd6OVmUoweTvspUX/A+kfp/hm6cBa9tgNKA7/rNskUF32NsSmxgKy4LS0C9noS5zcUKIhw9/vg/KvQHMqLqQ27cXgzL9hxV35dn4pmtFmnX4o04GZgq0vKM7WnDskU0W57Q8Elf81Nwmnd6t1xfk83ksVut3eVSnPB7aNdNADjj9/FWsJTP/CtytDdD/oSTHHufhiIUiM/+uR/GyCUGIXrNYs6w+NH3Vo6MsimJk03Fyc+VnlxU1R9uSLUwPgQLe+t2tige4u/xcoRiXZII564mg13JaI3r53DgIfuBzP0vnz8gNNqC+469ZaFT3b/8c81knzu1FKd0hhHhw+kWAS6BpIj1EzZbBmJkhxKxVgMYV40DNpCJ3KCfniA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
